# Project FORESIGHT

## Phase 8: Feature Engineering

### Objective

Create new features from the cleaned dataset to improve the performance of demand forecasting models.

In [19]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [20]:
df = pd.read_csv("../data/processed/cleaned_master_dataset.csv")

df["date"] = pd.to_datetime(df["date"])

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

C:\Users\user\AppData\Local\Temp\ipykernel_21632\1960261401.py:1: DtypeWarning: Columns (0: promo_event) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/cleaned_master_dataset.csv")

In [21]:
df.head()

        date  sku_id  units_sold  revenue  unit_price  promo_flag    category subcategory launch_date  unit_cost  list_price  week  month  season  is_holiday promo_event  on_hand_units  on_order_units  lead_time_days  reorder_point
0 2024-01-01  SKU001          16  3814.08      238.38           0  Appliances     General  2023-01-01        173      238.38     1      1  Winter           0         NaN          171.0            95.0            13.0           71.0
1 2024-01-01  SKU002           9   943.65      104.85           0   Furniture     General  2023-01-01         72      104.85     1      1  Winter           0         NaN           78.0            59.0             5.0           29.0
2 2024-01-01  SKU003          14  4658.92      332.78           0   Furniture     General  2023-01-01        183      332.78     1      1  Winter           0         NaN          135.0            86.0            15.0           74.0
3 2024-01-01  SKU004          11  2825.35      256.85           0   Furniture     General  2023-01-01        161      256.85     1      1  Winter           0         NaN          207.0            11.0            15.0           20.0
4 2024-01-01  SKU005          12   575.40       47.95           0   Furniture     General  2023-01-01         33       47.95     1      1  Winter           0         NaN          155.0            68.0             6.0           49.0

In [22]:
print(df.shape)

df.info()

(73000, 20)
<class 'pandas.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            73000 non-null  datetime64[us]
 1   sku_id          73000 non-null  str
 2   units_sold      73000 non-null  int64
 3   revenue         73000 non-null  float64
 4   unit_price      73000 non-null  float64
 5   promo_flag      73000 non-null  int64
 6   category        73000 non-null  str
 7   subcategory     73000 non-null  str
 8   launch_date     73000 non-null  str
 9   unit_cost       73000 non-null  int64
 10  list_price      73000 non-null  float64
 11  week            73000 non-null  int64
 12  month           73000 non-null  int64
 13  season          73000 non-null  str
 14  is_holiday      73000 non-null  int64
 15  promo_event     1600 non-null   str
 16  on_hand_units   9600 non-null   float64
 17  on_order_units  9600 non-null   float64
 18  lead_time_days  9600 non-null   float64
 19  reorder_point   9600 non-null   float64
dtypes: datetime64[us](1), float64(7), int64(6), str(6)
memory usage: 11.1 MB

In [23]:
df["year"] = df["date"].dt.year

df["quarter"] = df["date"].dt.quarter

df["month"] = df["date"].dt.month

df["day"] = df["date"].dt.day

df["day_of_week"] = df["date"].dt.day_of_week

df["day_name"] = df["date"].dt.day_name()

df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [24]:
df.head()

        date  sku_id  units_sold  revenue  unit_price  promo_flag    category subcategory launch_date  unit_cost  list_price  week  month  season  is_holiday promo_event  on_hand_units  on_order_units  lead_time_days  reorder_point  year  quarter  day  day_of_week day_name  is_weekend
0 2024-01-01  SKU001          16  3814.08      238.38           0  Appliances     General  2023-01-01        173      238.38     1      1  Winter           0         NaN          171.0            95.0            13.0           71.0  2024        1    1            0   Monday           0
1 2024-01-01  SKU002           9   943.65      104.85           0   Furniture     General  2023-01-01         72      104.85     1      1  Winter           0         NaN           78.0            59.0             5.0           29.0  2024        1    1            0   Monday           0
2 2024-01-01  SKU003          14  4658.92      332.78           0   Furniture     General  2023-01-01        183      332.78     1      1  Winter           0         NaN          135.0            86.0            15.0           74.0  2024        1    1            0   Monday           0
3 2024-01-01  SKU004          11  2825.35      256.85           0   Furniture     General  2023-01-01        161      256.85     1      1  Winter           0         NaN          207.0            11.0            15.0           20.0  2024        1    1            0   Monday           0
4 2024-01-01  SKU005          12   575.40       47.95           0   Furniture     General  2023-01-01         33       47.95     1      1  Winter           0         NaN          155.0            68.0             6.0           49.0  2024        1    1            0   Monday           0

In [25]:
df.head()

        date  sku_id  units_sold  revenue  unit_price  promo_flag    category subcategory launch_date  unit_cost  list_price  week  month  season  is_holiday promo_event  on_hand_units  on_order_units  lead_time_days  reorder_point  year  quarter  day  day_of_week day_name  is_weekend
0 2024-01-01  SKU001          16  3814.08      238.38           0  Appliances     General  2023-01-01        173      238.38     1      1  Winter           0         NaN          171.0            95.0            13.0           71.0  2024        1    1            0   Monday           0
1 2024-01-01  SKU002           9   943.65      104.85           0   Furniture     General  2023-01-01         72      104.85     1      1  Winter           0         NaN           78.0            59.0             5.0           29.0  2024        1    1            0   Monday           0
2 2024-01-01  SKU003          14  4658.92      332.78           0   Furniture     General  2023-01-01        183      332.78     1      1  Winter           0         NaN          135.0            86.0            15.0           74.0  2024        1    1            0   Monday           0
3 2024-01-01  SKU004          11  2825.35      256.85           0   Furniture     General  2023-01-01        161      256.85     1      1  Winter           0         NaN          207.0            11.0            15.0           20.0  2024        1    1            0   Monday           0
4 2024-01-01  SKU005          12   575.40       47.95           0   Furniture     General  2023-01-01         33       47.95     1      1  Winter           0         NaN          155.0            68.0             6.0           49.0  2024        1    1            0   Monday           0

In [26]:
import os

print(os.listdir("../data/processed"))

['cleaned_master_dataset.csv', 'feature_engineered_dataset.csv', 'master_dataset.csv']

In [28]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_master_dataset.csv")

print(df.shape)

(73000, 20)

C:\Users\user\AppData\Local\Temp\ipykernel_21632\3708528693.py:3: DtypeWarning: Columns (0: promo_event) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/cleaned_master_dataset.csv")

In [30]:
df["day"] = pd.to_datetime(df["date"]).dt.day
df["day_of_week"] = pd.to_datetime(df["date"]).dt.dayofweek
df["quarter"] = pd.to_datetime(df["date"]).dt.quarter
df["year"] = pd.to_datetime(df["date"]).dt.year

In [31]:
print(df.shape)
df.head()

(73000, 24)

         date  sku_id  units_sold  revenue  unit_price  promo_flag    category subcategory launch_date  unit_cost  list_price  week  month  season  is_holiday promo_event  on_hand_units  on_order_units  lead_time_days  reorder_point  day  day_of_week  quarter  year
0  2024-01-01  SKU001          16  3814.08      238.38           0  Appliances     General  2023-01-01        173      238.38     1      1  Winter           0         NaN          171.0            95.0            13.0           71.0    1            0        1  2024
1  2024-01-01  SKU002           9   943.65      104.85           0   Furniture     General  2023-01-01         72      104.85     1      1  Winter           0         NaN           78.0            59.0             5.0           29.0    1            0        1  2024
2  2024-01-01  SKU003          14  4658.92      332.78           0   Furniture     General  2023-01-01        183      332.78     1      1  Winter           0         NaN          135.0            86.0            15.0           74.0    1            0        1  2024
3  2024-01-01  SKU004          11  2825.35      256.85           0   Furniture     General  2023-01-01        161      256.85     1      1  Winter           0         NaN          207.0            11.0            15.0           20.0    1            0        1  2024
4  2024-01-01  SKU005          12   575.40       47.95           0   Furniture     General  2023-01-01         33       47.95     1      1  Winter           0         NaN          155.0            68.0             6.0           49.0    1            0        1  2024

In [32]:
df.to_csv(
    "../data/processed/feature_engineered_dataset.csv",
    index=False
)

print("Feature Engineered Dataset Saved Successfully")

Feature Engineered Dataset Saved Successfully

In [33]:
import os

print(os.path.getsize("../data/processed/feature_engineered_dataset.csv"))

7945190