In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Final Data Validation Started")
print("=" * 50)

# Project root
PROJECT_ROOT = Path("..")

# Final processed dataset
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "feature_engineered_dataset.csv"

print("Dataset path:")
print(DATA_PATH.resolve())

# Check file exists
if not DATA_PATH.exists():
    print("\n ERROR: Dataset file not found!")
else:
    print("\n Dataset file found!")

Final Data Validation Started
==================================================
Dataset path:
C:\Users\user\Documents\Zidio_Project\FORESIGHT\data\processed\feature_engineered_dataset.csv

 Dataset file found!

In [2]:
# Step 2: Load and inspect the final dataset

df = pd.read_csv(DATA_PATH)

print("Dataset Loaded Successfully")
print("=" * 50)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

C:\Users\user\AppData\Local\Temp\ipykernel_7092\2042467483.py:3: DtypeWarning: Columns (0: promo_event) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH)

Dataset Loaded Successfully
==================================================
Rows: 73000
Columns: 24

Column Names:
['date', 'sku_id', 'units_sold', 'revenue', 'unit_price', 'promo_flag', 'category', 'subcategory', 'launch_date', 'unit_cost', 'list_price', 'week', 'month', 'season', 'is_holiday', 'promo_event', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point', 'day', 'day_of_week', 'quarter', 'year']

First 5 Rows:

,date,sku_id,units_sold,revenue,unit_price,promo_flag,category,subcategory,launch_date,unit_cost,...,is_holiday,promo_event,on_hand_units,on_order_units,lead_time_days,reorder_point,day,day_of_week,quarter,year
0,2024-01-01,SKU001,16,3814.08,238.38,0,Appliances,General,2023-01-01,173,...,0,NaN,171.0,95.0,13.0,71.0,1,0,1,2024
1,2024-01-01,SKU002,9,943.65,104.85,0,Furniture,General,2023-01-01,72,...,0,NaN,78.0,59.0,5.0,29.0,1,0,1,2024
2,2024-01-01,SKU003,14,4658.92,332.78,0,Furniture,General,2023-01-01,183,...,0,NaN,135.0,86.0,15.0,74.0,1,0,1,2024
3,2024-01-01,SKU004,11,2825.35,256.85,0,Furniture,General,2023-01-01,161,...,0,NaN,207.0,11.0,15.0,20.0,1,0,1,2024
4,2024-01-01,SKU005,12,575.40,47.95,0,Furniture,General,2023-01-01,33,...,0,NaN,155.0,68.0,6.0,49.0,1,0,1,2024

In [4]:
# Step 3: Missing Values Validation

missing_values = df.isnull().sum()

print("Missing Values Validation")
print("=" * 50)

print(missing_values)

total_missing = missing_values.sum()

print("\nTotal Missing Values:", total_missing)

if total_missing == 0:
    print(" PASS: No missing values found.")
else:
    print(" WARNING: Missing values found.")

Missing Values Validation
==================================================
date                  0
sku_id                0
units_sold            0
revenue               0
unit_price            0
promo_flag            0
category              0
subcategory           0
launch_date           0
unit_cost             0
list_price            0
week                  0
month                 0
season                0
is_holiday            0
promo_event       71400
on_hand_units     63400
on_order_units    63400
lead_time_days    63400
reorder_point     63400
day                   0
day_of_week           0
quarter               0
year                  0
dtype: int64

Total Missing Values: 325000
 WARNING: Missing values found.

In [5]:
# Step 4: Detailed Missing Value Analysis

print("Detailed Missing Value Analysis")
print("=" * 50)

missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary = missing_summary[missing_summary["Missing_Count"] > 0]

print(missing_summary)

Detailed Missing Value Analysis
==================================================
                Missing_Count  Missing_Percentage
promo_event             71400               97.81
on_hand_units           63400               86.85
on_order_units          63400               86.85
lead_time_days          63400               86.85
reorder_point           63400               86.85

In [6]:
# Step 5: Investigate Missing Inventory Data

print("Missing Inventory Data Investigation")
print("=" * 50)

inventory_cols = [
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point"
]

print("\nMissing values by column:")
print(df[inventory_cols].isnull().sum())

print("\nRows where inventory data is missing:")
missing_inventory = df[df[inventory_cols].isnull().any(axis=1)]

print("Number of affected rows:", len(missing_inventory))

print("\nSample affected rows:")
display(
    missing_inventory[
        ["date", "sku_id"] + inventory_cols
    ].head(10)
)

Missing Inventory Data Investigation
==================================================

Missing values by column:
on_hand_units     63400
on_order_units    63400
lead_time_days    63400
reorder_point     63400
dtype: int64

Rows where inventory data is missing:
Number of affected rows: 63400

Sample affected rows:

,date,sku_id,on_hand_units,on_order_units,lead_time_days,reorder_point
200,2024-01-02,SKU001,NaN,NaN,NaN,NaN
201,2024-01-02,SKU002,NaN,NaN,NaN,NaN
202,2024-01-02,SKU003,NaN,NaN,NaN,NaN
203,2024-01-02,SKU004,NaN,NaN,NaN,NaN
204,2024-01-02,SKU005,NaN,NaN,NaN,NaN
205,2024-01-02,SKU006,NaN,NaN,NaN,NaN
206,2024-01-02,SKU007,NaN,NaN,NaN,NaN
207,2024-01-02,SKU008,NaN,NaN,NaN,NaN
208,2024-01-02,SKU009,NaN,NaN,NaN,NaN
209,2024-01-02,SKU010,NaN,NaN,NaN,NaN

In [7]:
# Step 6: Check Missing Inventory Pattern

print("Missing Inventory Pattern")
print("=" * 50)

print("\nDate range of missing inventory rows:")
print("Start:", missing_inventory["date"].min())
print("End:", missing_inventory["date"].max())

print("\nNumber of unique SKUs affected:")
print(missing_inventory["sku_id"].nunique())

print("\nTop affected SKUs:")
print(missing_inventory["sku_id"].value_counts().head(10))

print("\nMissing inventory rows by date:")
print(missing_inventory["date"].value_counts().head(10))

Missing Inventory Pattern
==================================================

Date range of missing inventory rows:
Start: 2024-01-02
End: 2024-12-30

Number of unique SKUs affected:
200

Top affected SKUs:
sku_id
SKU001    317
SKU002    317
SKU003    317
SKU004    317
SKU005    317
SKU006    317
SKU007    317
SKU008    317
SKU009    317
SKU010    317
Name: count, dtype: int64

Missing inventory rows by date:
date
2024-01-02    200
2024-01-03    200
2024-01-04    200
2024-01-05    200
2024-01-06    200
2024-01-07    200
2024-01-09    200
2024-01-10    200
2024-01-11    200
2024-01-12    200
Name: count, dtype: int64

In [8]:
# Step 7: Validate Original Inventory Data

inventory_path = PROJECT_ROOT / "data" / "raw" / "inventory_snapshots.csv"

print("Original Inventory Data Validation")
print("=" * 50)

print("Inventory file path:")
print(inventory_path.resolve())

if inventory_path.exists():
    inventory_df = pd.read_csv(inventory_path)

    print("\n Original inventory file found!")
    print("Rows:", inventory_df.shape[0])
    print("Columns:", inventory_df.shape[1])

    print("\nColumns:")
    print(inventory_df.columns.tolist())

    print("\nMissing values in original inventory data:")
    print(inventory_df.isnull().sum())

else:
    print("\n Original inventory file NOT found!")

Original Inventory Data Validation
==================================================
Inventory file path:
C:\Users\user\Documents\Zidio_Project\FORESIGHT\data\raw\inventory_snapshots.csv

 Original inventory file found!
Rows: 9600
Columns: 6

Columns:
['date', 'sku_id', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point']

Missing values in original inventory data:
date              0
sku_id            0
on_hand_units     0
on_order_units    0
lead_time_days    0
reorder_point     0
dtype: int64

In [9]:
# Step 8: Compare Inventory Coverage

print("Inventory Coverage Check")
print("=" * 50)

print("\nFinal Dataset:")
print("Date range:", df["date"].min(), "to", df["date"].max())
print("Unique SKUs:", df["sku_id"].nunique())

print("\nOriginal Inventory:")
print("Date range:", inventory_df["date"].min(), "to", inventory_df["date"].max())
print("Unique SKUs:", inventory_df["sku_id"].nunique())

print("\nOriginal Inventory Rows:", len(inventory_df))

print("\nExpected inventory combinations:")
print(
    inventory_df["date"].nunique()
    * inventory_df["sku_id"].nunique()
)

Inventory Coverage Check
==================================================

Final Dataset:
Date range: 2024-01-01 to 2024-12-30
Unique SKUs: 200

Original Inventory:
Date range: 2024-01-01 to 2024-12-22
Unique SKUs: 200

Original Inventory Rows: 9600

Expected inventory combinations:
9600

In [10]:
# Step 9: Check Date + SKU Matching

print("Date + SKU Matching Validation")
print("=" * 50)

# Make sure date types match
df["date"] = pd.to_datetime(df["date"])
inventory_df["date"] = pd.to_datetime(inventory_df["date"])

# Create matching keys
final_keys = set(zip(df["date"], df["sku_id"]))
inventory_keys = set(zip(inventory_df["date"], inventory_df["sku_id"]))

matched_keys = final_keys.intersection(inventory_keys)

print("Unique Date + SKU combinations in final dataset:", len(final_keys))
print("Unique Date + SKU combinations in inventory:", len(inventory_keys))
print("Matching Date + SKU combinations:", len(matched_keys))
print("Non-matching combinations:", len(final_keys - inventory_keys))

# Check actual inventory rows that should match
match_mask = [
    (date, sku) in inventory_keys
    for date, sku in zip(df["date"], df["sku_id"])
]

print("\nFinal dataset rows with matching inventory:")
print(sum(match_mask))

print("Final dataset rows without matching inventory:")
print(len(df) - sum(match_mask))

Date + SKU Matching Validation
==================================================
Unique Date + SKU combinations in final dataset: 73000
Unique Date + SKU combinations in inventory: 9600
Matching Date + SKU combinations: 9600
Non-matching combinations: 63400

Final dataset rows with matching inventory:
9600
Final dataset rows without matching inventory:
63400

In [11]:
# Step 10: Inventory Date Coverage

print("Inventory Date Coverage")
print("=" * 50)

inventory_date_counts = inventory_df.groupby("date").size()

print("Number of inventory dates:", len(inventory_date_counts))

print("\nFirst 10 inventory dates:")
print(inventory_date_counts.head(10))

print("\nLast 10 inventory dates:")
print(inventory_date_counts.tail(10))

print("\nRows per inventory date:")
print(inventory_date_counts.value_counts().sort_index())

Inventory Date Coverage
==================================================
Number of inventory dates: 48

First 10 inventory dates:
date
2024-01-01    200
2024-01-08    200
2024-01-15    200
2024-01-22    200
2024-02-01    200
2024-02-08    200
2024-02-15    200
2024-02-22    200
2024-03-01    200
2024-03-08    200
dtype: int64

Last 10 inventory dates:
date
2024-10-15    200
2024-10-22    200
2024-11-01    200
2024-11-08    200
2024-11-15    200
2024-11-22    200
2024-12-01    200
2024-12-08    200
2024-12-15    200
2024-12-22    200
dtype: int64

Rows per inventory date:
200    48
Name: count, dtype: int64

In [12]:
# Step 11: Display All Inventory Snapshot Dates

print("All Inventory Snapshot Dates")
print("=" * 50)

snapshot_dates = sorted(inventory_df["date"].unique())

for i, date in enumerate(snapshot_dates, start=1):
    print(f"{i:02d}. {pd.Timestamp(date).date()}")

All Inventory Snapshot Dates
==================================================
01. 2024-01-01
02. 2024-01-08
03. 2024-01-15
04. 2024-01-22
05. 2024-02-01
06. 2024-02-08
07. 2024-02-15
08. 2024-02-22
09. 2024-03-01
10. 2024-03-08
11. 2024-03-15
12. 2024-03-22
13. 2024-04-01
14. 2024-04-08
15. 2024-04-15
16. 2024-04-22
17. 2024-05-01
18. 2024-05-08
19. 2024-05-15
20. 2024-05-22
21. 2024-06-01
22. 2024-06-08
23. 2024-06-15
24. 2024-06-22
25. 2024-07-01
26. 2024-07-08
27. 2024-07-15
28. 2024-07-22
29. 2024-08-01
30. 2024-08-08
31. 2024-08-15
32. 2024-08-22
33. 2024-09-01
34. 2024-09-08
35. 2024-09-15
36. 2024-09-22
37. 2024-10-01
38. 2024-10-08
39. 2024-10-15
40. 2024-10-22
41. 2024-11-01
42. 2024-11-08
43. 2024-11-15
44. 2024-11-22
45. 2024-12-01
46. 2024-12-08
47. 2024-12-15
48. 2024-12-22

In [14]:
# Step 12: Test As-Of Inventory Coverage - Corrected

print("As-Of Inventory Coverage Test")
print("=" * 50)

# Prepare daily data
daily_df = df[["date", "sku_id"]].copy()

# Prepare inventory data
inventory_test = inventory_df[
    [
        "date",
        "sku_id",
        "on_hand_units",
        "on_order_units",
        "lead_time_days",
        "reorder_point"
    ]
].copy()

# Make sure dates are datetime
daily_df["date"] = pd.to_datetime(daily_df["date"])
inventory_test["date"] = pd.to_datetime(inventory_test["date"])

# Sort by date first, then SKU
daily_df = daily_df.sort_values(["date", "sku_id"]).reset_index(drop=True)
inventory_test = inventory_test.sort_values(["date", "sku_id"]).reset_index(drop=True)

# As-of matching
test_merged = pd.merge_asof(
    daily_df,
    inventory_test,
    on="date",
    by="sku_id",
    direction="backward"
)

inventory_cols = [
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point"
]

print("Rows tested:", len(test_merged))

print("\nMissing values after as-of matching:")
print(test_merged[inventory_cols].isnull().sum())

total_missing_after = test_merged[inventory_cols].isnull().sum().sum()

print("\nTotal inventory missing after as-of matching:", total_missing_after)

if total_missing_after == 0:
    print(" PASS: All daily rows can receive an inventory snapshot.")
else:
    print(" Some inventory values still cannot be matched.")

As-Of Inventory Coverage Test
==================================================
Rows tested: 73000

Missing values after as-of matching:
on_hand_units     0
on_order_units    0
lead_time_days    0
reorder_point     0
dtype: int64

Total inventory missing after as-of matching: 0
 PASS: All daily rows can receive an inventory snapshot.

In [15]:
# Step 13: Apply As-Of Inventory Data to Final Dataset

print("Applying As-Of Inventory Data")
print("=" * 50)

# Keep the original final dataset columns
feature_cols = [
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point"
]

# Remove the currently incorrect inventory columns
df_base = df.drop(columns=feature_cols)

# Prepare inventory data
inventory_final = inventory_df[
    ["date", "sku_id"] + feature_cols
].copy()

# Ensure datetime format
df_base["date"] = pd.to_datetime(df_base["date"])
inventory_final["date"] = pd.to_datetime(inventory_final["date"])

# Sort for merge_asof
df_base = df_base.sort_values(["date", "sku_id"]).reset_index(drop=True)
inventory_final = inventory_final.sort_values(["date", "sku_id"]).reset_index(drop=True)

# Apply latest available inventory snapshot
df_fixed = pd.merge_asof(
    df_base,
    inventory_final,
    on="date",
    by="sku_id",
    direction="backward"
)

print("Original rows:", len(df))
print("Fixed rows:", len(df_fixed))

print("\nMissing inventory values after correction:")
print(df_fixed[feature_cols].isnull().sum())

total_inventory_missing = df_fixed[feature_cols].isnull().sum().sum()

print("\nTotal inventory missing:", total_inventory_missing)

if total_inventory_missing == 0:
    print("PASS: Inventory data successfully applied to all rows.")
else:
    print("FAIL: Inventory values are still missing.")

Applying As-Of Inventory Data
==================================================
Original rows: 73000
Fixed rows: 73000

Missing inventory values after correction:
on_hand_units     0
on_order_units    0
lead_time_days    0
reorder_point     0
dtype: int64

Total inventory missing: 0
PASS: Inventory data successfully applied to all rows.

In [16]:
# Step 14: Investigate Promo Event Missing Values

print("Promo Event Validation")
print("=" * 50)

print("Missing promo_event values:")
print(df_fixed["promo_event"].isnull().sum())

print("\nNon-missing promo_event values:")
print(df_fixed["promo_event"].notnull().sum())

print("\nUnique promo_event values:")
print(df_fixed["promo_event"].value_counts(dropna=False))

print("\nPromo event data type:")
print(df_fixed["promo_event"].dtype)

Promo Event Validation
==================================================
Missing promo_event values:
71400

Non-missing promo_event values:
1600

Unique promo_event values:
promo_event
NaN         71400
Festival     1600
Name: count, dtype: int64

Promo event data type:
str

In [17]:
# Step 15: Validate Original Calendar Data

calendar_path = PROJECT_ROOT / "data" / "raw" / "calender.csv"

print("Original Calendar Data Validation")
print("=" * 50)

print("Calendar file path:")
print(calendar_path.resolve())

if calendar_path.exists():
    calendar_df = pd.read_csv(calendar_path)

    print("\nOriginal calendar file found!")

    print("Rows:", calendar_df.shape[0])
    print("Columns:", calendar_df.shape[1])

    print("\nColumns:")
    print(calendar_df.columns.tolist())

    print("\nMissing values:")
    print(calendar_df.isnull().sum())

    print("\nPromo event values:")
    print(calendar_df["promo_event"].value_counts(dropna=False))

else:
    print("\nOriginal calendar file NOT found!")

Original Calendar Data Validation
==================================================
Calendar file path:
C:\Users\user\Documents\Zidio_Project\FORESIGHT\data\raw\calender.csv

Original calendar file NOT found!

In [18]:
# Step 16: Find Calendar File

raw_path = PROJECT_ROOT / "data" / "raw"

print("Files inside data/raw:")
print("=" * 50)

for file in raw_path.iterdir():
    print(file.name)

Files inside data/raw:
==================================================
calendar.csv
inventory_snapshots.csv
sales_daily.csv
sku_master.csv

In [19]:
# Step 17: Validate Original Calendar Data

calendar_path = PROJECT_ROOT / "data" / "raw" / "calendar.csv"

print("Original Calendar Data Validation")
print("=" * 50)

print("Calendar file path:")
print(calendar_path.resolve())

if calendar_path.exists():
    calendar_df = pd.read_csv(calendar_path)

    print("\nOriginal calendar file found!")

    print("Rows:", calendar_df.shape[0])
    print("Columns:", calendar_df.shape[1])

    print("\nColumns:")
    print(calendar_df.columns.tolist())

    print("\nMissing values:")
    print(calendar_df.isnull().sum())

    print("\nPromo event values:")
    print(calendar_df["promo_event"].value_counts(dropna=False))

else:
    print("\nOriginal calendar file NOT found!")

Original Calendar Data Validation
==================================================
Calendar file path:
C:\Users\user\Documents\Zidio_Project\FORESIGHT\data\raw\calendar.csv

Original calendar file found!
Rows: 365
Columns: 6

Columns:
['date', 'week', 'month', 'season', 'is_holiday', 'promo_event']

Missing values:
date             0
week             0
month            0
season           0
is_holiday       0
promo_event    357
dtype: int64

Promo event values:
promo_event
NaN         357
Festival      8
Name: count, dtype: int64

In [20]:
# Step 18: Handle Missing Promo Events

print("Handling Promo Event Values")
print("=" * 50)

print("Before:")
print(df_fixed["promo_event"].value_counts(dropna=False))

# Replace missing promo events with explicit "No_Event"
df_fixed["promo_event"] = df_fixed["promo_event"].fillna("No_Event")

print("\nAfter:")
print(df_fixed["promo_event"].value_counts(dropna=False))

# Validate
missing_promo = df_fixed["promo_event"].isnull().sum()

print("\nMissing promo_event values:", missing_promo)

if missing_promo == 0:
    print("PASS: promo_event has no missing values.")
else:
    print("FAIL: promo_event still contains missing values.")

Handling Promo Event Values
==================================================
Before:
promo_event
NaN         71400
Festival     1600
Name: count, dtype: int64

After:
promo_event
No_Event    71400
Festival     1600
Name: count, dtype: int64

Missing promo_event values: 0
PASS: promo_event has no missing values.

In [21]:
# Step 19: Final Missing Value Validation

print("FINAL MISSING VALUE VALIDATION")
print("=" * 50)

missing_final = df_fixed.isnull().sum()

print(missing_final)

total_missing_final = missing_final.sum()

print("\nTotal Missing Values:", total_missing_final)

if total_missing_final == 0:
    print("\nPASS: Final dataset contains NO missing values.")
else:
    print("\nFAIL: Missing values still exist.")
    
    print("\nColumns with missing values:")
    print(missing_final[missing_final > 0])

FINAL MISSING VALUE VALIDATION
==================================================
date              0
sku_id            0
units_sold        0
revenue           0
unit_price        0
promo_flag        0
category          0
subcategory       0
launch_date       0
unit_cost         0
list_price        0
week              0
month             0
season            0
is_holiday        0
promo_event       0
day               0
day_of_week       0
quarter           0
year              0
on_hand_units     0
on_order_units    0
lead_time_days    0
reorder_point     0
dtype: int64

Total Missing Values: 0

PASS: Final dataset contains NO missing values.

In [22]:
# Step 20: Duplicate Records Validation

print("DUPLICATE RECORDS VALIDATION")
print("=" * 50)

duplicate_count = df_fixed.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

if duplicate_count == 0:
    print("\nPASS: No duplicate rows found.")
else:
    print("\nFAIL: Duplicate rows found.")
    
    print("\nSample duplicate rows:")
    display(df_fixed[df_fixed.duplicated(keep=False)].head(10))

DUPLICATE RECORDS VALIDATION
==================================================
Total duplicate rows: 0

PASS: No duplicate rows found.

In [23]:
# Step 21: Data Type Validation

print("DATA TYPE VALIDATION")
print("=" * 50)

print("\nCurrent Data Types:")
print(df_fixed.dtypes)

# Expected datetime columns
datetime_columns = [
    "date",
    "launch_date"
]

# Expected numeric columns
numeric_columns = [
    "units_sold",
    "revenue",
    "unit_price",
    "promo_flag",
    "unit_cost",
    "list_price",
    "week",
    "month",
    "is_holiday",
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point",
    "day",
    "day_of_week",
    "quarter",
    "year"
]

print("\nDatetime Validation:")
datetime_errors = []

for col in datetime_columns:
    if not pd.api.types.is_datetime64_any_dtype(df_fixed[col]):
        datetime_errors.append(col)
        print(f"{col}: NOT datetime")
    else:
        print(f"{col}: datetime")

print("\nNumeric Validation:")
numeric_errors = []

for col in numeric_columns:
    if not pd.api.types.is_numeric_dtype(df_fixed[col]):
        numeric_errors.append(col)
        print(f"{col}: NOT numeric")
    else:
        print(f"{col}: numeric")

print("\nValidation Summary")

if len(datetime_errors) == 0 and len(numeric_errors) == 0:
    print("PASS: All expected data types are correct.")
else:
    print("FAIL: Some data types need correction.")
    print("Datetime errors:", datetime_errors)
    print("Numeric errors:", numeric_errors)

DATA TYPE VALIDATION
==================================================

Current Data Types:
date              datetime64[us]
sku_id                       str
units_sold                 int64
revenue                  float64
unit_price               float64
promo_flag                 int64
category                     str
subcategory                  str
launch_date                  str
unit_cost                  int64
list_price               float64
week                       int64
month                      int64
season                       str
is_holiday                 int64
promo_event                  str
day                        int64
day_of_week                int64
quarter                    int64
year                       int64
on_hand_units              int64
on_order_units             int64
lead_time_days             int64
reorder_point              int64
dtype: object

Datetime Validation:
date: datetime
launch_date: NOT datetime

Numeric Validation:
units_sold: numeric
revenue: numeric
unit_price: numeric
promo_flag: numeric
unit_cost: numeric
list_price: numeric
week: numeric
month: numeric
is_holiday: numeric
on_hand_units: numeric
on_order_units: numeric
lead_time_days: numeric
reorder_point: numeric
day: numeric
day_of_week: numeric
quarter: numeric
year: numeric

Validation Summary
FAIL: Some data types need correction.
Datetime errors: ['launch_date']
Numeric errors: []

In [24]:
# Step 22: Correct launch_date Data Type

print("Correcting launch_date Data Type")
print("=" * 50)

# Convert launch_date to datetime
df_fixed["launch_date"] = pd.to_datetime(
    df_fixed["launch_date"],
    errors="coerce"
)

print("launch_date dtype:", df_fixed["launch_date"].dtype)

# Check if conversion created missing values
invalid_launch_dates = df_fixed["launch_date"].isnull().sum()

print("Invalid/missing launch_date values:", invalid_launch_dates)

if invalid_launch_dates == 0:
    print("PASS: launch_date successfully converted to datetime.")
else:
    print("FAIL: Invalid launch_date values found.")

Correcting launch_date Data Type
==================================================
launch_date dtype: datetime64[us]
Invalid/missing launch_date values: 0
PASS: launch_date successfully converted to datetime.

In [25]:
# Step 23: Final Data Type Revalidation

print("FINAL DATA TYPE VALIDATION")
print("=" * 50)

datetime_columns = [
    "date",
    "launch_date"
]

numeric_columns = [
    "units_sold",
    "revenue",
    "unit_price",
    "promo_flag",
    "unit_cost",
    "list_price",
    "week",
    "month",
    "is_holiday",
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point",
    "day",
    "day_of_week",
    "quarter",
    "year"
]

datetime_errors = []
numeric_errors = []

print("\nDatetime columns:")

for col in datetime_columns:
    if pd.api.types.is_datetime64_any_dtype(df_fixed[col]):
        print(f"{col}")
    else:
        print(f"{col}")
        datetime_errors.append(col)

print("\nNumeric columns:")

for col in numeric_columns:
    if pd.api.types.is_numeric_dtype(df_fixed[col]):
        print(f"{col}")
    else:
        print(f"{col}")
        numeric_errors.append(col)

print("\nValidation Summary")

if not datetime_errors and not numeric_errors:
    print("PASS: All expected data types are correct.")
else:
    print("FAIL")
    print("Datetime errors:", datetime_errors)
    print("Numeric errors:", numeric_errors)

FINAL DATA TYPE VALIDATION
==================================================

Datetime columns:
date
launch_date

Numeric columns:
units_sold
revenue
unit_price
promo_flag
unit_cost
list_price
week
month
is_holiday
on_hand_units
on_order_units
lead_time_days
reorder_point
day
day_of_week
quarter
year

Validation Summary
PASS: All expected data types are correct.

In [26]:
# Step 24: Date Range Validation

print("DATE VALIDATION")
print("=" * 50)

print("Main date range:")
print("Start:", df_fixed["date"].min())
print("End:", df_fixed["date"].max())

print("\nLaunch date range:")
print("Start:", df_fixed["launch_date"].min())
print("End:", df_fixed["launch_date"].max())

print("\nInvalid date values:")

invalid_main_dates = df_fixed["date"].isna().sum()
invalid_launch_dates = df_fixed["launch_date"].isna().sum()

print("Invalid date:", invalid_main_dates)
print("Invalid launch_date:", invalid_launch_dates)

print("\nValidation Summary")

if invalid_main_dates == 0 and invalid_launch_dates == 0:
    print("PASS: All date values are valid.")
else:
    print("FAIL: Invalid date values found.")

DATE VALIDATION
==================================================
Main date range:
Start: 2024-01-01 00:00:00
End: 2024-12-30 00:00:00

Launch date range:
Start: 2023-01-01 00:00:00
End: 2023-01-01 00:00:00

Invalid date values:
Invalid date: 0
Invalid launch_date: 0

Validation Summary
PASS: All date values are valid.

In [27]:
# Step 25: Numeric and Business Rule Validation

print("NUMERIC & BUSINESS-RULE VALIDATION")
print("=" * 50)

checks = {
    "units_sold_negative": (df_fixed["units_sold"] < 0).sum(),
    "revenue_negative": (df_fixed["revenue"] < 0).sum(),
    "unit_price_negative": (df_fixed["unit_price"] < 0).sum(),
    "unit_cost_negative": (df_fixed["unit_cost"] < 0).sum(),
    "list_price_negative": (df_fixed["list_price"] < 0).sum(),
    "on_hand_units_negative": (df_fixed["on_hand_units"] < 0).sum(),
    "on_order_units_negative": (df_fixed["on_order_units"] < 0).sum(),
    "lead_time_days_negative": (df_fixed["lead_time_days"] < 0).sum(),
    "reorder_point_negative": (df_fixed["reorder_point"] < 0).sum()
}

for check, count in checks.items():
    print(f"{check}: {count}")

print("\nValidation Summary")

if all(count == 0 for count in checks.values()):
    print("PASS: No invalid negative values found.")
else:
    print("WARNING: Some negative values were found.")

NUMERIC & BUSINESS-RULE VALIDATION
==================================================
units_sold_negative: 0
revenue_negative: 0
unit_price_negative: 0
unit_cost_negative: 0
list_price_negative: 0
on_hand_units_negative: 0
on_order_units_negative: 0
lead_time_days_negative: 0
reorder_point_negative: 0

Validation Summary
PASS: No invalid negative values found.

In [28]:
# Step 26: Final Dataset Consistency Check

print("FINAL DATASET CONSISTENCY CHECK")
print("=" * 50)

expected_rows = 73000
expected_columns = 24
expected_skus = 200

actual_rows = len(df_fixed)
actual_columns = len(df_fixed.columns)
actual_skus = df_fixed["sku_id"].nunique()
unique_date_sku = df_fixed[["date", "sku_id"]].drop_duplicates().shape[0]

print("Rows:", actual_rows)
print("Columns:", actual_columns)
print("Unique SKUs:", actual_skus)
print("Unique Date + SKU combinations:", unique_date_sku)

print("\nExpected:")
print("Rows:", expected_rows)
print("Columns:", expected_columns)
print("SKUs:", expected_skus)
print("Date + SKU combinations:", expected_rows)

print("\nValidation Summary")

if (
    actual_rows == expected_rows
    and actual_columns == expected_columns
    and actual_skus == expected_skus
    and unique_date_sku == expected_rows
):
    print("PASS: Final dataset consistency is correct.")
else:
    print("FAIL: Final dataset consistency check failed.")

FINAL DATASET CONSISTENCY CHECK
==================================================
Rows: 73000
Columns: 24
Unique SKUs: 200
Unique Date + SKU combinations: 73000

Expected:
Rows: 73000
Columns: 24
SKUs: 200
Date + SKU combinations: 73000

Validation Summary
PASS: Final dataset consistency is correct.

In [29]:
# Step 27: Save Final Validated Dataset

final_output_path = PROJECT_ROOT / "data" / "processed" / "feature_engineered_dataset_final.csv"

df_fixed.to_csv(final_output_path, index=False)

print("FINAL DATASET SAVE")
print("=" * 50)

print("Saved to:")
print(final_output_path.resolve())

print("\nRows saved:", len(df_fixed))
print("Columns saved:", len(df_fixed.columns))

if final_output_path.exists():
    print("\nPASS: Final validated dataset saved successfully.")
else:
    print("\nFAIL: Final dataset was not saved.")

FINAL DATASET SAVE
==================================================
Saved to:
C:\Users\user\Documents\Zidio_Project\FORESIGHT\data\processed\feature_engineered_dataset_final.csv

Rows saved: 73000
Columns saved: 24

PASS: Final validated dataset saved successfully.

In [30]:
# Step 28: Verify Final Saved Dataset

print("FINAL SAVED DATASET VERIFICATION")
print("=" * 50)

final_check = pd.read_csv(final_output_path)

print("File exists:", final_output_path.exists())
print("Rows:", len(final_check))
print("Columns:", len(final_check.columns))
print("Missing values:", final_check.isnull().sum().sum())
print("Duplicate rows:", final_check.duplicated().sum())
print("Unique SKUs:", final_check["sku_id"].nunique())

if (
    len(final_check) == 73000
    and len(final_check.columns) == 24
    and final_check.isnull().sum().sum() == 0
    and final_check.duplicated().sum() == 0
    and final_check["sku_id"].nunique() == 200
):
    print("\nFINAL DATA VALIDATION: PASS")
else:
    print("\nFINAL DATA VALIDATION: FAIL")

FINAL SAVED DATASET VERIFICATION
==================================================
File exists: True
Rows: 73000
Columns: 24
Missing values: 0
Duplicate rows: 0
Unique SKUs: 200

FINAL DATA VALIDATION: PASS

In [31]:
from pathlib import Path

print("Notebook files")
print("=" * 50)

notebooks_path = Path.cwd().parent / "notebooks"

print("Checking:", notebooks_path.resolve())

if notebooks_path.exists():
    for file in sorted(notebooks_path.glob("*.ipynb")):
        print("-", file.name)
else:
    print("notebooks folder not found")

Notebook files
==================================================
Checking: C:\Users\user\Documents\Zidio_Project\FORESIGHT\notebooks
- 01_data_understanding.ipynb
- 02_data_cleaning.ipynb
- 03_data_engineering.ipynb
- 04_eda.ipynb
- 05_feature_engineering.ipynb
- 06_baseline_forecasting.ipynb
- 07_model_evaluation.ipynb
- 08_risk_scoring.ipynb
- 09_final_data_validation.ipynb

In [32]:
from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent

print("Project Root:")
print(PROJECT_ROOT.resolve())

Project Root:
C:\Users\user\Documents\Zidio_Project\FORESIGHT